Крылов Дмитрий Эдуардович, Б05-202, контест 1, задача E, посылка 71415102
dm1trykrylov/algo-course pull request #3
Opened 2022-10-06 19:31 UTC by dm1trykrylov

2022-10-09 19:15 UTC, VladislavHacker requested changes

2022-10-09 19:15 UTC, VladislavHacker commented on .gitignore
> +*.txt
удали мусор

2022-10-09 19:15 UTC, VladislavHacker commented on main.cpp
> +    std::cout << "error";
не выводи в методах, возвращай true - если успех, false если неудача

2022-10-09 19:15 UTC, VladislavHacker commented on main.cpp
> +    std::cout << "error";
не выводи в методах, возвращай true - если успех, false если неудача (это касается всех методов)

2022-10-10 11:45 UTC, dm1trykrylov commented on main.cpp
> +    std::cout << "error";
Исправил, теперь вывод в одной функции

2022-10-14 16:03 UTC, dm1trykrylov commented
Я убрал методы с выводом, а проверку делаю с помощью std::optional

2022-10-14 20:46 UTC, VladislavHacker commented
Not bad

2022-10-14 20:47 UTC, VladislavHacker approved these changes

2022-10-14 20:47 UTC, VladislavHacker commented on main.cpp
> +const int kInf = 1e9 + 2;
nimeric limits
есть

2022-10-24 21:54 UTC, merged